<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Debu_Lenovo" failures="4" tests="10" name="Employee page test" time="53.132" errors="0" timestamp="2024-02-02T12:51:42 IST">
  <testcase classname="test_runner.PIMTestRunner" name="doLoginWithInvalidCreds" time="3.339"/>
  <testcase classname="test_runner.PIMTestRunner" name="doLogin" time="5.852"/>
  <testcase classname="test_runner.PIMTestRunner" name="createEmployeeWithoutUsername" time="8.924"/>
  <testcase classname="test_runner.PIMTestRunner" name="createEmployee1" time="10.545"/>
  <testcase classname="test_runner.PIMTestRunner" name="createEmployee2" time="8.106"/>
  <testcase classname="test_runner.PIMTestRunner" name="searchEmployeeByInvalidName" time="4.202">
    <failure type="org.junit.ComparisonFailure" message="expected:&amp;lt;[No Records Found]&amp;gt; but was:&amp;lt;[Buzz]&amp;gt;">
      <![CDATA[org.junit.ComparisonFailure: expected:<[No Records Found]> but was:<[Buzz]>
at org.junit.Assert.assertEquals(Assert.java:125)
at org.junit.Assert.assertEquals(Assert.java:147)
at test_runner.PIMTestRunner.searchEmployeeByInvalidName(PIMTestRunner.java:145)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- searchEmployeeByInvalidName -->
  <testcase classname="test_runner.PIMTestRunner" name="searchEmployeeByName" time="3.186">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at test_runner.PIMTestRunner.searchEmployeeByName(PIMTestRunner.java:166)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- searchEmployeeByName -->
  <testcase classname="test_runner.PIMTestRunner" name="updateEmployeeById" time="0.033">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index 6 out of bounds for length 6">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index 6 out of bounds for length 6
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
at java.base/java.util.Objects.checkIndex(Objects.java:361)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementListHandler.invoke(LocatingElementListHandler.java:39)
at jdk.proxy2/jdk.proxy2.$Proxy12.get(Unknown Source)
at pages.PIMPage.updateEmployeeById(PIMPage.java:86)
at test_runner.PIMTestRunner.updateEmployeeById(PIMTestRunner.java:176)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- updateEmployeeById -->
  <testcase classname="test_runner.PIMTestRunner" name="searchEmployeeById" time="4.211">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.assertTrue(Assert.java:43)
at org.junit.Assert.assertTrue(Assert.java:54)
at test_runner.PIMTestRunner.searchEmployeeById(PIMTestRunner.java:198)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- searchEmployeeById -->
  <testcase classname="test_runner.PIMTestRunner" name="logOut" time="1.138"/>
</testsuite> <!-- Employee page test -->
